CREATE TABLE `geocodes` (
  `id` int(11) unsigned NOT null AUTO_INCREMENT,
  `timeCreated` datetime NOT null,
  `hash` char(40) NOT null DEFAULT '',
  `language` char(5) NOT null DEFAULT '',
  `number` varchar(10) NOT null DEFAULT '',
  `premise` varchar(10) NOT null DEFAULT '',
  `street` varchar(100) NOT null DEFAULT '',
  `neighborhood` varchar(100) NOT null DEFAULT '',
  `part` varchar(100) NOT null DEFAULT '',
  `city` varchar(100) NOT null DEFAULT '',
  `county` varchar(100) NOT null DEFAULT '',
  `district` varchar(100) NOT null DEFAULT '',
  `country` varchar(100) NOT null DEFAULT '',
  `zip` varchar(10) NOT null DEFAULT '',
  `formatted` varchar(255) NOT null DEFAULT '',
  `lat` double(10,7) NOT null,
  `lng` double(10,7) NOT null,
  PRIMARY KEY (`id`),
  KEY `hash` (`hash`),
  KEY `language` (`language`),
  KEY `latlng` (`lat`,`lng`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;